"""ale_test

Revision ID: b5ce4c103598
Revises: 3ceec084158f
Create Date: 2023-07-24 20:39:25.780418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ce4c103598'
down_revision = '3ceec084158f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
