FROM mongo:latest

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3-pip \
    python3-dev \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-setuptools

WORKDIR /app

COPY requirements.txt .
RUN pip3 install -r requirements.txt


