version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
  app:
    build:
      context: ./app
    ports:
      - "4040:80"
    depends_on:
      - api
