FROM python:3.8.10-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY ./hosthome.py ./
COPY data ./data
COPY blueprints ./blueprints
COPY config ./config

EXPOSE 8080

CMD ["python", "hosthome.py"]
