server {

        root /var/www/homeunite.us/html;
        # index index.html;
        index index.html index.htm index.nginx-debian.html;

        server_name homeunite.us www.homeunite.us;

        location / {
                try_files $uri $uri/ /index.html =404;
        }


        location /api/ {
           include proxy_params;
           proxy_pass http://unix:/opt/homeuniteus/homeuniteus.sock;
        }

}
