#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['app',
 'app.modules',
 'app.modules.access',
 'app.modules.intake_profile',
 'app.modules.matching',
 'app.modules.onboarding',
 'app.modules.relationship_management',
 'app.modules.tenant_housing_orgs',
 'app.modules.workflow']

package_data = \
{'': ['*'],
 'app': ['core/*'],
 'app.modules.intake_profile': ['forms/*'],
 'app.modules.workflow': ['dashboards/*', 'dashboards/coordinator/*']}

setup(name='app',
      version='1.0.0',
      description='Home Unite Us',
      author=None,
      author_email='Hack for LA <homeuniteus@hackforla.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.12',
     )