/* tslint:disable */
/* eslint-disable */
/**
 * Home Unite Us
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Host
 */
export interface Host {
    /**
     * 
     * @type {number}
     * @memberof Host
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Host
     */
    tag?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Host
     */
    photoUrls?: Array<string>;
}

export function HostFromJSON(json: any): Host {
    return HostFromJSONTyped(json, false);
}

export function HostFromJSONTyped(json: any, ignoreDiscriminator: boolean): Host {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'tag': !exists(json, 'tag') ? undefined : json['tag'],
        'photoUrls': !exists(json, 'photoUrls') ? undefined : json['photoUrls'],
    };
}

export function HostToJSON(value?: Host | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'tag': value.tag,
        'photoUrls': value.photoUrls,
    };
}

