"""Dashboard users view.

Revision ID: 281f96d4d453
Revises: fead8af85db5
Create Date: 2024-11-04 20:58:09.765444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '281f96d4d453'
down_revision = 'fead8af85db5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_users_view', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('dashboard_users_view', sa.Column('name', sa.String(), nullable=False))
    op.add_column('dashboard_users_view', sa.Column('status', sa.String(), nullable=False))
    op.add_column('dashboard_users_view', sa.Column('coordinator_name', sa.String(), nullable=False))
    op.add_column('dashboard_users_view', sa.Column('updated', sa.DateTime(), nullable=False))
    op.drop_column('dashboard_users_view', 'id')
    op.drop_column('dashboard_users_view', 'caseStatus')
    op.drop_column('dashboard_users_view', 'userName')
    op.drop_column('dashboard_users_view', 'lastUpdated')
    op.drop_column('dashboard_users_view', 'coordinatorName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_users_view', sa.Column('coordinatorName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('dashboard_users_view', sa.Column('lastUpdated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('dashboard_users_view', sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('dashboard_users_view', sa.Column('caseStatus', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('dashboard_users_view', sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('dashboard_users_view', 'updated')
    op.drop_column('dashboard_users_view', 'coordinator_name')
    op.drop_column('dashboard_users_view', 'status')
    op.drop_column('dashboard_users_view', 'name')
    op.drop_column('dashboard_users_view', 'user_id')
    # ### end Alembic commands ###
