/* tslint:disable */
/* eslint-disable */
/**
 * Home Unite Us
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Guest,
    GuestFromJSON,
    GuestToJSON,
    ModelApiResponse,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
} from '../models';

export interface ShowGuestByIdRequest {
    guestId: string;
}

/**
 * 
 */
export class GuestsApi extends runtime.BaseAPI {

    /**
     * Info for a specific guest
     */
    async showGuestByIdRaw(requestParameters: ShowGuestByIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Guest>> {
        if (requestParameters.guestId === null || requestParameters.guestId === undefined) {
            throw new runtime.RequiredError('guestId','Required parameter requestParameters.guestId was null or undefined when calling showGuestById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/guests/{guestId}`.replace(`{${"guestId"}}`, encodeURIComponent(String(requestParameters.guestId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuestFromJSON(jsonValue));
    }

    /**
     * Info for a specific guest
     */
    async showGuestById(requestParameters: ShowGuestByIdRequest, initOverrides?: RequestInit): Promise<Guest> {
        const response = await this.showGuestByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
