/* tslint:disable */
/* eslint-disable */
/**
 * Home Unite Us
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Host,
    HostFromJSON,
    HostToJSON,
    ModelApiResponse,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
} from '../models';

export interface ShowHostByIdRequest {
    hostId: string;
}

/**
 * 
 */
export class HostsApi extends runtime.BaseAPI {

    /**
     * Info for a specific host
     */
    async showHostByIdRaw(requestParameters: ShowHostByIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Host>> {
        if (requestParameters.hostId === null || requestParameters.hostId === undefined) {
            throw new runtime.RequiredError('hostId','Required parameter requestParameters.hostId was null or undefined when calling showHostById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hosts/{hostId}`.replace(`{${"hostId"}}`, encodeURIComponent(String(requestParameters.hostId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HostFromJSON(jsonValue));
    }

    /**
     * Info for a specific host
     */
    async showHostById(requestParameters: ShowHostByIdRequest, initOverrides?: RequestInit): Promise<Host> {
        const response = await this.showHostByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
