/* tslint:disable */
/* eslint-disable */
/**
 * Home Unite Us
 * Hack for LA - Home Unite Us API server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Host,
    HostFromJSON,
    HostToJSON,
} from '../models';

export interface AddHostRequest {
    host?: Host;
}

/**
 * 
 */
export class HostApi extends runtime.BaseAPI {

    /**
     * Add a new host to the program
     */
    async addHostRaw(requestParameters: AddHostRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/host`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HostToJSON(requestParameters.host),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a new host to the program
     */
    async addHost(requestParameters: AddHostRequest): Promise<void> {
        await this.addHostRaw(requestParameters);
    }

}
