# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Guest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, tag=None, photo_urls=None):  # noqa: E501
        """Guest - a model defined in OpenAPI

        :param id: The id of this Guest.  # noqa: E501
        :type id: int
        :param name: The name of this Guest.  # noqa: E501
        :type name: str
        :param tag: The tag of this Guest.  # noqa: E501
        :type tag: str
        :param photo_urls: The photo_urls of this Guest.  # noqa: E501
        :type photo_urls: List[str]
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'tag': str,
            'photo_urls': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'tag': 'tag',
            'photo_urls': 'photoUrls'
        }

        self._id = id
        self._name = name
        self._tag = tag
        self._photo_urls = photo_urls

    @classmethod
    def from_dict(cls, dikt) -> 'Guest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Guest of this Guest.  # noqa: E501
        :rtype: Guest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Guest.


        :return: The id of this Guest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Guest.


        :param id: The id of this Guest.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Guest.


        :return: The name of this Guest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Guest.


        :param name: The name of this Guest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def tag(self):
        """Gets the tag of this Guest.


        :return: The tag of this Guest.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this Guest.


        :param tag: The tag of this Guest.
        :type tag: str
        """

        self._tag = tag

    @property
    def photo_urls(self):
        """Gets the photo_urls of this Guest.


        :return: The photo_urls of this Guest.
        :rtype: List[str]
        """
        return self._photo_urls

    @photo_urls.setter
    def photo_urls(self, photo_urls):
        """Sets the photo_urls of this Guest.


        :param photo_urls: The photo_urls of this Guest.
        :type photo_urls: List[str]
        """

        self._photo_urls = photo_urls
