# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.service_provider import ServiceProvider
from openapi_server import util

from openapi_server.models.service_provider import ServiceProvider  # noqa: E501

class ServiceProviderWithId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, provider_name=None):  # noqa: E501
        """ServiceProviderWithId - a model defined in OpenAPI

        :param id: The id of this ServiceProviderWithId.  # noqa: E501
        :type id: int
        :param provider_name: The provider_name of this ServiceProviderWithId.  # noqa: E501
        :type provider_name: str
        """
        self.openapi_types = {
            'id': int,
            'provider_name': str
        }

        self.attribute_map = {
            'id': 'id',
            'provider_name': 'provider_name'
        }

        self._id = id
        self._provider_name = provider_name

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceProviderWithId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceProviderWithId of this ServiceProviderWithId.  # noqa: E501
        :rtype: ServiceProviderWithId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ServiceProviderWithId.


        :return: The id of this ServiceProviderWithId.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ServiceProviderWithId.


        :param id: The id of this ServiceProviderWithId.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def provider_name(self):
        """Gets the provider_name of this ServiceProviderWithId.


        :return: The provider_name of this ServiceProviderWithId.
        :rtype: str
        """
        return self._provider_name

    @provider_name.setter
    def provider_name(self, provider_name):
        """Sets the provider_name of this ServiceProviderWithId.


        :param provider_name: The provider_name of this ServiceProviderWithId.
        :type provider_name: str
        """
        if provider_name is None:
            raise ValueError("Invalid value for `provider_name`, must not be `None`")  # noqa: E501

        self._provider_name = provider_name
