name: Build application
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd app && npm ci
      - run: cd app && npm run build
      - run: cd app && npm run test
      - name: Run E2E tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          project: ./app
          start: run run dev
          wait-on: http://localhost:4040
