name: Build and Deploy to EC2
#on: workflow_dispatch
on: pull_request
jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./api
    outputs:
      sdist: ${{ steps.package.outputs.sdist }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 500
          fetch-tags: true
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
#      - name: Install API dev Dependencies
#        run: |
#          pip install -r requirements-dev.txt
#      - name: Test with tox
#        run: |
#          # Use tox because it is configured to test against the same package type being deployed
#          tox
      - name: Build API Deployment Package
        id: package
        run: |
          python -m pip install build
          SDIST=$(python -m build --sdist | perl -n -e '/^Successfully built (.*)\.tar\.gz$/ && print $1')
          [ -n "$SDIST" ] && echo "sdist=$SDIST" >> "$GITHUB_OUTPUT"
      - name: Archive API Deployment Package
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: api/dist
          retention-days: 7
  build-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - name: Run npm CI
        run: npm ci
      - name: Build app
        run: npm run build
     # - name: Test app
     #   run: npm run test
     # - name: Run E2E tests
     #   uses: cypress-io/github-action@v5
     #   with:
     #     install: false
     #     start: npm run dev
     #     working-directory: ./app
     #     wait-on: http://localhost:4040
      - name: Archive App
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/dist
          retention-days: 7
  deploy-api-app:
    needs: [build-api, build-app]
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HUU_EC2_SSH_KEY }}
          # The value below is the server's PUBLIC key. It's a required attribute for this action.
          known_hosts: homeunite.us ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu/AdtdkNgDuezmkVeENDtC1Mf2erROKDEslMj+RFwuXj5CuLG2PRNTpzebgVlIJwxrq76+QWEFFG4gub2+mq2N+FlQ/if+R+a3Ym7lS3J25usgBliO6Dgp3Oxuq6n3V3/SopXIZ3/p8zGyBOiEjF8NXXy6y/ByfqT61jhZZR4MuMxdsaTbOI8wYfCAkxJTRn7E3U36iZNxgyxl5LCw97AxxiAzzg+f4GmpY7JuNy0EEqAEdRHPs6LBjrmDw6QLkDVS7AEA64yF8cDqDtNdB4Q/SkmJ0AyggU+fkFJ+wq01+mjtBMfjlaMmk+a2KowCIU6L+Mo2E7FnbQ0vKBg4iY3
      - name: rsync over SSH API and App to EC2
        run: |
          # upload the api and app directories to the EC2 instance
          rsync --mkpath -r app ubuntu@homeunite.us:github-deploy/
          rsync --mkpath -r api ubuntu@homeunite.us:github-deploy/
          # /home/ubuntu/github-deploy/api contains the sdist
          # /home/ubuntu/github-deploy/app contains the frontend app source
      - name: Configure EC2
        uses: appleboy/ssh-action@v1.0.0
        env:
          SDIST: ${{needs.build-api.outputs.sdist}}
        with:
          host: homeunite.us
          username: ubuntu
          key: ${{ secrets.HUU_EC2_SSH_KEY }}
          script_stop: true
          envs: SDIST
          script: |
            # TODO: Run database migration scripts
            cd /home/ubuntu
            ./create_archive.bash

            # Update database

            # Deploy API
            cd /home/ubuntu/github-deploy/api
            source /opt/dev.homeunite.us/dev-huu-env/bin/activate
            pip uninstall -y -r <(pip freeze) || echo "Nothing to uninstall"
            pip install --upgrade pip
            pip install -r <(tar xfO $SDIST.tar.gz $SDIST/requirements.txt)
            pip install "$SDIST.tar.gz[prod]"
            deactivate
            sudo systemctl restart dev-homeuniteus-api.service
            rm -rf /home/ubuntu/github-deploy/api/*

            # Deploy front-end app
            cd /home/ubuntu/github-deploy/app
            sudo rsync -a * /var/www/dev.homeunite.us/html/
            rm -r /home/ubuntu/github-deploy/app/*
